# Generated by Django 3.1.1 on 2020-09-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whentoremind',
            name='only_remind_when_open',
            field=models.BooleanField(null=True),
        ),
    ]
