# Generated by Django 3.1.1 on 2020-09-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='status',
            field=models.CharField(default='', max_length=15),
        ),
    ]
