# Generated by Django 3.1.1 on 2020-09-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.TextField(default='closed'),
            preserve_default=False,
        ),
    ]
