# Generated by Django 3.1.1 on 2020-10-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20200929_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='num_spots_taken',
            field=models.CharField(default='', max_length=20),
        ),
    ]
