# Generated by Django 3.1.1 on 2020-09-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20200920_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='section',
            field=models.ManyToManyField(blank=True, null=True, to='course.Section'),
        ),
    ]
