# Generated by Django 3.1.1 on 2020-10-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_section_num_spots_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='num_spots_taken',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
