# Generated by Django 3.1.1 on 2020-10-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20201001_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='status',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
