# Generated by Django 3.1.1 on 2020-09-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20200928_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='abbrev',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
