# Generated by Django 3.1.1 on 2020-10-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20201006_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='num_spots_taken',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='section',
            name='status',
            field=models.CharField(default='', max_length=50),
        ),
    ]
